class Jamun
{
public static void main(String[] args) 
{
 String Name="Krishna";
 System.out.println(Name);
 String nam="karna";
 System.out.println(nam);
 String peru="arjuna";
 System.out.println(peru);
 String esaru="balarama";
 System.out.println(esaru);
 String hello="duryodana";
 System.out.println(hello);
 
 String lila="shakuni";
 System.out.println(lila);
 String tata="kaurava";
 System.out.println(tata);
 String majunu="pandava";
 System.out.println(majunu);
 String yo="dharmaraju";
 System.out.println(yo);
 String yes="bemudu";
 System.out.println(yes);
 String no="nakuludu";
 System.out.println(no);
 String maha="ashwathama";
 System.out.println(maha);
 String baratham="panchangi";
 System.out.println(baratham);
 String kuroo="hanuma";
 System.out.println(kuroo);
 String hell="drawpathi";
 System.out.println(hell);
 String he="gathoj gathudu";
 System.out.println(he);
 String she="dushyasanduu";
 System.out.println(she);
 String ba="dronacharya";
 System.out.println(ba);
 String va="parshuramudu";
 System.out.println(va);
 String katha="ganga";
 System.out.println(katha);
 String stiry="bahubalii";
 System.out.println(stiry);
 String sana="balladeva";
 System.out.println(sana);
 String ata="devasena";
 System.out.println(ata);
 String bat="mahasena";
 System.out.println(bat);
 String cricket="shivagami";
 System.out.println(cricket);
 String adios="katappa";
 System.out.println(adios);
 String bata="yudham";
 System.out.println(bata);
 String cat="vijayam";
 System.out.println(cat);
 String rama = "tree";
System.out.println(rama);
String sita = "mountain";
System.out.println(sita);
String lakshmana = "river";
System.out.println(lakshmana);
String bharata = "sun";
System.out.println(bharata);
String shatrughna = "moon";
System.out.println(shatrughna);
String hanuman = "star";
System.out.println(hanuman);
String sugriva = "ocean";
System.out.println(sugriva);
String vibhishana = "flower";
System.out.println(vibhishana);
String ravana = "forest";
System.out.println(ravana);
String kaikeyi = "desert";
System.out.println(kaikeyi);
String kausalya = "rain";
System.out.println(kausalya);
String sumitra = "cloud";
System.out.println(sumitra);
String indrajit = "rock";
System.out.println(indrajit);
String angada = "hill";
System.out.println(angada);
String jatayu = "sand";
System.out.println(jatayu);
String sampati = "grass";
System.out.println(sampati);
String tara = "leaf";
System.out.println(tara);
String mandodari = "bird";
System.out.println(mandodari);
String vali = "butterfly";
System.out.println(vali);
String lanka = "insect";
System.out.println(lanka);
String sita_1 = "fish";
System.out.println(sita_1);
String dasharatha = "animal";
System.out.println(dasharatha);
String janaka = "reptile";
System.out.println(janaka);
String surpanakha = "amphibian";
System.out.println(surpanakha);
String kumbhakarna = "tree";
System.out.println(kumbhakarna);
String vishwamitra = "mountain";
System.out.println(vishwamitra);
String aghasura = "river";
System.out.println(aghasura);
String maricha = "sun";
System.out.println(maricha);
String jatayu_1 = "moon";
System.out.println(jatayu_1);
String sugreeva = "star";
System.out.println(sugreeva);
String jambavan = "ocean";
System.out.println(jambavan);
String hanuman_1 = "flower";
System.out.println(hanuman_1);
String lanka_1 = "forest";
System.out.println(lanka_1);
String vanara = "desert";
System.out.println(vanara);
String ayodhya = "rain";
System.out.println(ayodhya);
String chitrakoot = "cloud";
System.out.println(chitrakoot);
String panchavati = "rock";
System.out.println(panchavati);
String lanka_2 = "hill";
System.out.println(lanka_2);
String sita_2 = "sand";
System.out.println(sita_2);
String rama_1 = "grass";
System.out.println(rama_1);
String lakshmana_1 = "leaf";
System.out.println(lakshmana_1);
String bharata_1 = "bird";
System.out.println(bharata_1);
String shatrughna_1 = "butterfly";
System.out.println(shatrughna_1);
String hanuman_2 = "insect";
System.out.println(hanuman_2);
String sugriva_1 = "fish";
System.out.println(sugriva_1);
String vibhishana_1 = "animal";
System.out.println(vibhishana_1);
String ravana_1 = "reptile";
System.out.println(ravana_1);
String kaikeyi_1 = "amphibian";
System.out.println(kaikeyi_1);
String kausalya_1 = "tree";
System.out.println(kausalya_1);
String sumitra_1 = "mountain";
System.out.println(sumitra_1);
String indrajit_1 = "river";
System.out.println(indrajit_1);
String angada_1 = "sun";
System.out.println(angada_1);
String jatayu_2 = "moon";
System.out.println(jatayu_2);
String sampati_1 = "star";
System.out.println(sampati_1);
String tara_1 = "ocean";
System.out.println(tara_1);
String mandodari_1 = "flower";
System.out.println(mandodari_1);
 }
}
